### ISSUE TITLE
Cannot pass a test name with special characters via an input file

### ISSUE THREAD

**Issue by igor-akhmetov** [catchorg/Catch2#1767]
I can't seem to pass the name of a test with special characters via an input file, specifically the one from CmdLine.tests.cpp:
```
TEST_CASE("Test with special, characters \"in name", "[cli][regression]") {
    // This test case succeeds if we can invoke it from the CLI
    SUCCEED();
}
```
`--list-test-names-only` outputs `Test with special, characters "in name`, which does not allow to run the test:
```
C:\src\Catch2\build\projects\Debug>SelfTest.exe -f tests.txt
Filters: "Test with special, characters "in name",
No test cases matched '"Test with special'
No test cases matched 'characters "in name"'
===============================================================================
No tests ran
```
I'd expect
```
Test with special\, characters \"in name
```
or
```
"Test with special\, characters \"in name"
```
to work, but they don't:
```
C:\src\Catch2\build\projects\Debug>SelfTest.exe -f tests.txt
Filters: "Test with special\, characters \"in name",
No test cases matched '"Test with special\, characters \"in name"'
===============================================================================
No tests ran


C:\src\Catch2\build\projects\Debug>SelfTest.exe -f tests.txt
Filters: "Test with special\, characters \"in name",
No test cases matched '"Test with special\, characters \"in name"'
===============================================================================
No tests ran
```

**Comment by amitherman95** [comment]
Try updating the single header file by executing <Catch2 path>/scripts/generateSingleHeader.py

**Comment by igor-akhmetov** [comment]
Same with names like `vector<int,allocator> -> toString`, escaping a comma in the input file does not seem to help.

**Comment by igor-akhmetov** [comment]
@amitherman95 How is the single header relevant here? This is with the latest version of Catch2, I just grab the latest source, build, and run SelfTest.exe.

**Comment by amitherman95** [comment]
Oh I see, I'll check it out

**Comment by echuber2** [comment]
I'm also experiencing this. Commas in test case names break stuff. This used to work in older versions of Catch (at least, it worked in v2.2.3). Now, with v2.9.2, it's causing issues. I do note that when I search through the v.2.9.2 catch.hpp file, there is one part that says:

> // Applies the function macro `f` to each of the remaining parameters, inserts commas between the results,
// and passes userdata as the first parameter to each invocation,

I wonder if that's the problem, or if it's doing something else. For now I'm just going to avoid allowing commas in test case names. Colons and hyphens seem okay. I can't show the specific code I'm running unfortunately.

**Comment by echuber2** [comment]
Update: Semicolons also seem okay. For now I'll replace commas in test names with semicolons then.

**Comment by amitherman95** [comment]
I found the cause of the problem, will upload PR later in the day

**Comment by amitherman95** [comment]
That should fix the problem

**Comment by horenmar** [comment]
This is fixed in master now.

**Comment by igor-akhmetov** [comment]
Thanks a lot for the quick fix!
One note however: --list-test-names-only still does not quote special characters in test names, so "This makes it ideal for saving to a file and feeding back into the -f or --input-file option" from the documentation does not hold.
In general, am I correct that it's necessary to escape only '~', '"', ',', '[' and ']' characters in test names when feeding them back to Catch2 via an input file?

**Comment by horenmar** [comment]
For the first, I'll have to think about it a bit -- I prefer to output human readable names to outputting round-trippable name (and the `--list-test-names-only` flag is going away anyway).

For the second, I cannot think of more right now, but it is important to note that `*` currently cannot be escaped (but you can have it as a part of a test name).
