### ISSUE TITLE
Problems installing Catch2 `v3.0.0-preview3` from sources

### ISSUE THREAD

**Issue by robamu** [catchorg/Catch2#2326]
I try to build a fixed version with the following commands as specified in https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md#top .  

```sh
git clone https://github.com/catchorg/Catch2.git
cd Catch2
cmake -Bbuild -H. -DBUILD_TESTING=OFF
sudo cmake --build build/ --target install
```

**Platform information:**
- OS: Ubuntu 21.04
 - Compiler+version: **GCC 11.2.0**
 - Catch version: **v3.0.0-preview3**

# Error

```
In file included from /usr/include/signal.h:328,
                 from /home/rmueller/Software/Catch2/src/catch2/../catch2/internal/catch_fatal_condition_handler.hpp:37,
                 from /home/rmueller/Software/Catch2/src/catch2/internal/catch_fatal_condition_handler.cpp:8:
/home/rmueller/Software/Catch2/src/catch2/internal/catch_fatal_condition_handler.cpp:94:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
   94 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /home/rmueller/Software/Catch2/src/catch2/../catch2/internal/catch_fatal_condition_handler.hpp:37,
                 from /home/rmueller/Software/Catch2/src/catch2/internal/catch_fatal_condition_handler.cpp:8:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
/home/rmueller/Software/Catch2/src/catch2/internal/catch_fatal_condition_handler.cpp:150:45: error: size of array ‘altStackMem’ is not an integral constant-expression
  150 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
gmake[2]: *** [src/CMakeFiles/Catch2.dir/build.make:433: src/CMakeFiles/Catch2.dir/catch2/internal/catch_fatal_condition_handler.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:142: src/CMakeFiles/Catch2.dir/all] Error 2
gmake: *** [Makefile:171: all] Error 2
```

On `develop` it compiles. I think it would be good to make a new preview release because the last tag https://github.com/catchorg/Catch2/tree/v3.0.0-preview3 is already ~2 years old / 300-400 commits behind. We had the issue that I compiled unittests with Catch2 based on `develop`, and then the tests failed on a CI/CD server which fetched  `v3.0.0-preview3`. We don't really want to fetch unstable `develop` , but we'd like to use some features which are not part of `v3.0.0-preview3` so a new intermediate release would be good. What do you think?

**Comment by ASmoliak** [comment]
You're in luck. I managed to reproduce this issue as well, but on a newer distro, and much older catch version:

**OS:** Ubuntu 21.10
**Compiler+version:** GCC 11.2.0
**Catch version:** v2.13

It has nothing to do with the version, but seemingly with the compiler version

the issue is that the value of MINSIGSTKSZ stops being hardcoded after a certain version of GCC, and begins to actually query the value using the syscall `sysconf`:

![image](https://user-images.githubusercontent.com/26040470/145392978-15831d6e-ec9d-4a71-8a2c-d1ded2d46d33.png)

The problem is that catch2 uses that macro when initializing constexpr which is in compile time, now that it calls a syscall it can only be discovered in runtime, so the fix is very simple: removing `constexpr` and use `static const inline` instead.

Then what will happen is that we are allocating an "alt signal stack" memory that is just a plain old array which takes said constexpr that does not work anymore, but it can no longer be evaluated because we cannot determine the value in compile time anymore.

the solution to that line is to allocate the memory in a dynamic container, like a vector:

` std::vector<char> FatalConditionHandler::altStackMem(sigStackSize, {});`

And then every other use of it needs to be fixed..

I'd contribute but I have no idea how to.

Either that, or to cease using MINSIGSTKSZ and begin assuming the size.

**Comment by horenmar** [comment]
@ASmoliak It is a libc version thing, but yes. It is also fixed in the current versions of both v2 and v3

@robamu Agreed that it has been a while since release, but I am taking a break until January.

**Comment by robamu** [comment]
No issues, enjoy your break :+1:

**Comment by skrueger8** [comment]
You still have the affected versions in your documentation, i.e.

https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md#cmake-targets
> GIT_TAG        v3.0.0-preview3

and

https://github.com/catchorg/Catch2/blob/v2.x/docs/cmake-integration.md
> GIT_TAG        v2.13.1)

So people (like me) will run into this when they follow your tutorials.
