### ISSUE TITLE
catch_amalgamated.cpp(8072,33): error C2593: 'operator <<' is ambiguous

### ISSUE THREAD

**Issue by pisoir** [catchorg/Catch2#2916]
**Describe the bug**
I am using the latest 3.7.1 version of `catch_amalgamated.hpp` and  `catch_amalgamated.cpp` and I have a simple example file, tests.cpp:

```
#include "catch_amalgamated.hpp"

unsigned int Factorial(unsigned int number) {
    return number <= 1 ? number : Factorial(number - 1) * number;
}
TEST_CASE("Factorials are computed", "[test]") {
    REQUIRE(Factorial(1) == 1);
    REQUIRE(Factorial(2) == 2);
    REQUIRE(Factorial(3) == 6);
    REQUIRE(Factorial(10) == 3628800);
}
```

When I try to compile it (in Visual Studio 2019, C++17), I get many of these compilation errors:

```
catch_amalgamated.cpp(8072,33): error C2593: 'operator <<' is ambiguous
catch_amalgamated.cpp(6598,10): message : could be 'std::ostream &Catch::operator <<(std::ostream &,Catch::StringRef)'
catch_amalgamated.hpp(773,30): message : or       'std::ostream &Catch::operator <<(std::ostream &,Catch::StringRef)' [found using argument-dependent lookup]
catch_amalgamated.cpp(8072,33): message : while trying to match the argument list '(std::basic_ostream<char,std::char_traits<char>>, Catch::StringRef)'
catch_amalgamated.cpp(8106,33): error C2593: 'operator <<' is ambiguous
```
 
Any idea why?

**Expected behavior**
The code should compile.

**Reproduction steps**
1. Copy `catch_amalgamated.hpp` and  `catch_amalgamated.cpp`  to the solution folder
2. In the Visual Studio add both files to the project.
3. Build project -> error

**Platform information:**
 - OS: **Windows 10**
 - Compiler+version: **Visual Studio 2019**
 - Catch version: **v3.7.1**

**Comment by pisoir** [comment]
It seems that setting the flag `/permissive` (or `/Zc:hiddenFriend-`) fixes it. `(C/C++ -> Language -> Conformance mode -> No (/permissive))`
I would still like to understand what the problem is. Is this a bug in Visual Studio?

**Comment by horenmar** [comment]
This is a known MSVC (the compiler bundled in VS) bug, IIRC it is fixed in current versions.

What went wrong is that after decades of being non-conforming compiler, MSVC had a large project to bring themselves more in-line with the C++ standard. This new behaviour was hidden behind the `/permissive-` flag (which later became the default setting when creating new VS projects). However, in the process they introduced new fun bugs, like this one, where they improperly consider the **declaration** of a hidden friend function as a **definition** instead, so when they later find the actual definition, they report error because of two definitions.

----e----

[It was fixed in Aug 2021, so the fix is definitely in current released versions now](https://developercommunity.visualstudio.com/t/Wrong-diagnostic-of-ambiguous-operator-c/1403523)

**Comment by pisoir** [comment]
Ok. Thank you. It seems that for some strange reason they fixed it only in Visual Studio 2022. I have the latest version of 2019 and the bug is still there.

**Comment by horenmar** [comment]
2019 is in maintenance mode, except maintenance here means "CVEs" and not bugfixes.

**Comment by pisoir** [comment]
> 2019 is in maintenance mode, except maintenance here means "CVEs" and not bugfixes.

Yes, now. But when the bug was fixed in 2021 it could have been in a different mode (I don't know).
